# Le dice a SonarCloud cómo analizar tu proyecto
sonar.projectKey=Zeth-21_PruebasUnitarias_BrunoFerrini
sonar.organization=zeth-21

# Nombre del proyecto que aparece en el dashboard de SonarCloud
sonar.projectName=PruebasUnitarias_BrunoFerrini

# Qué archivos analizar (adaptado a tu estructura de carpetas)
sonar.sources=BrunoFerrini/src
sonar.tests=BrunoFerrini/tests

# Excluir node_modules y archivos de configuración
sonar.exclusions=node_modules/**,coverage/**

# Indicar dónde está el reporte de cobertura de Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8